config/routes.rb
Crmpro::Application.routes.draw do
  root :to => 'home#landing'
  get '/home' => 'home#home'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  get '/people' => 'people#index'
  resources :events
  resources :organisations do
  		member do
  			get :add_person
  			post :create_person
  		end
  end

  resources :people do
      member do
        get :add_event
        post :create_event
      end
  end

end

app/models/person.rb
# == Schema Information
#
# Table name: people
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  surname         :string(255)
#  address         :string(255)
#  mobile          :string(255)
#  email           :string(255)
#  state           :string(255)
#  notes           :string(255)
#  type            :string(255)
#  status          :string(255)
#  organisation_id :string(255)
#  country         :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string(255)
#  is_admin        :boolean          default(FALSE)
#

class Person < ActiveRecord::Base
	has_secure_password
  	attr_accessible :name, :id, :surname, :mobile, :email, :state, :country, :password, :password_confirmation
  	belongs_to	:organisation
  	has_many	:events

  	validates :mobile, :presence => true
  	validates :email, :uniqueness => true
	validates :name, :length => {:minimum => 2 }
	validates :surname, :uniqueness => true, :length => {:minimum => 2 }
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_filter :check_if_logged_in, :except => [:new, :create]
  before_filter :check_if_admin, :only => [:destroy]

  # GET /people
  # GET /people.json
  def index

    if params[:searchname] && params[:searchname].present? 
      @people = Person.where(:name => params[:searchname])
    else params[:searchsurname] && params[:searchsurname].present?
      @people = Person.where(:surname => params[:searchsurname])
    # else
    #   @people = Person.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @people }
    end
  end
  # GET /people/1
  # GET /people/1.json
  def show
    @person = Person.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/new
  # GET /people/new.json
  def new
    @person = Person.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/1/edit
  def edit
    @person = Person.find(params[:id])
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(params[:person])

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render json: @person, status: :created, location: @person }

      else
        format.html { render action: "new" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /people/1
  # PUT /people/1.json
  def update
    @person = Person.find(params[:id])

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end

  def add_event
    @person = Person.find(params[:id])
  end

  def create_event
    @person = Person.find(params[:id])
    @person.events << Event.find(params[:event])
    @person.save
    redirect_to @person
  end



  private
  def check_if_logged_in
    redirect_to(login_path) if @auth.nil?
  end

  def check_if_admin
    redirect_to(root_path) if @auth.nil? || !@auth.is_admin?
  end

end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= form_for @person do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name, :autofocus => true %>
  <br>
  <%= f.label :surname %>
  <%= f.text_field :surname %>
  <br>
  <%= f.label :mobile %>
  <%= f.text_field :mobile %>
  <br>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <br>
  <%= f.label :state %>
  <%= f.text_field :state %>
  <br>
  <%= f.label :country %>
  <%= f.text_field :country %>
  <br>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <br>
  <%= f.submit %>
<% end %>

app/views/people/add_event.html.erb
<%= form_tag [:create_event, @person] do %>

	<%= select_tag :event, options_from_collection_for_select(Event.all,:id, :eventtype) %>
	<%= submit_tag 'add' %>
<% end %>

app/views/people/create.html.erb
<h1>EventsController#create</h1>
<p>Find me in app/views/events_controller/create.html.erb</p>

app/views/people/destroy.html.erb
<h1>EventsController#destroy</h1>
<p>Find me in app/views/events_controller/destroy.html.erb</p>

app/views/people/edit.html.erb
<h1>Edit person</h1>
<%= render :partial => 'form' %>

app/views/people/index.html.erb
<div>
  <h3>Search for Person</h3>
    <h3>
      Results:
      <p id="peeps">
      <% @people.each do |person| %>
      <li><%= link_to(person.name, person) %> <%= link_to(person.surname, person) %></li>
      <% end %>
    </p>
    </h3>
      <%= form_tag people_path, :method => :get do %>
      <%= label_tag :name %>
      <%= text_field_tag :searchname %>
      <%= label_tag :surname %>
      <%= text_field_tag :searchsurname %>
    <br>
      <%= submit_tag 'search' %>
      <% end %>
    </p>
</div>

app/views/people/new.html.erb
<h1>Create New Person</h1>
<%= render :partial => 'form' %>

app/views/people/show.html.erb
<div class="container-fluid form_a">
  <div class="row-fluid">
  <div class="span6">
    <h1><%= @person.name %> <%= @person.surname %> </h1>
    <table class="table">
      <tr>
        <td>First Name: <%= @person.name %><td>Surname: <%= @person.surname%>
      </tr>
      <tr>
        <td>Address: <%= @person.address %><td><td> State: <%= @person.state%></td>
      </tr>
      <tr>
        <td>Email: <%= @person.email%><td><td>Mobile: <%= @person.mobile %><td>
      </tr>
      <tr>
        <td>Type: <%= @person.type %><td><td>Status: <%= @person.status %><td>
      </tr>
      <button><%= link_to 'Edit', edit_person_path(@person) %></button>
      <button><%= link_to 'Delete', @person, :method => :delete %></button>
      </p>
    </table>
  </div>
<div class="container-fluid form_b">
  <div class="row-fluid">
    <div class="span6">
      <h1>CALENDAR</h1>
      <div id="google"><iframe name="google" src="https://www.google.com/calendar/embed?src=qetsbt61e7bjh7iagu50tvia1c%40group.calendar.google.com&ctz=Australia/Sydney"></iframe></div>
    </div>
  <div class="row-fluid">
    <div class="span6">
      <h1>EVENT NOTES</h1>
      <table class="table">
      <tr><td><button><p><%= link_to 'Add new event to person', add_event_person_path(@person) %></p></button><td></tr>
    <ul>
      <% @person.events.each do |event| %>
      <li><%= event.eventtype %> <%= event.notes %> <%= event.startdate %></li>
      <% end %>
    </ul>
  <td><td>  <td><td>   <td></tr>
  </div>
</div>

app/views/people/update.html.erb
<h1>EventsController#update</h1>
<p>Find me in app/views/events_controller/update.html.erb</p>