config/routes.rb
Crmpro::Application.routes.draw do
  root :to => 'home#landing'
  get '/home' => 'home#home'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  get '/people' => 'people#index'
  resources :events
  resources :organisations do
  		member do
  			get :add_person
  			post :create_person
  		end
  end

  resources :people do
      member do
        get :add_event
        post :create_event
      end
  end

end

app/models/organisation.rb
# == Schema Information
#
# Table name: organisations
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  address    :string(255)
#  phone      :string(255)
#  state      :string(255)
#  country    :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Organisation < ActiveRecord::Base
  attr_accessible :name, :id, :phone, :state, :address
  has_many	:people
  #has_many :events, :through => :person
  #belongs_to :creator, :foreign_key => 'creator_id', :class_name => 'Person'
end

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController
  before_filter :authorize

  def authorize
    if @auth
    else
      redirect_to login_path
    end
  end
  # GET /organisations
  # GET /organisations.json
  def index
    @organisations = Organisation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @organisations }
    end
end
 # GET /organisations/1
  # GET /organisations/1.json
  def show
    @organisation = Organisation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @organisation }
    end
  end

  # GET /organisations/new
  # GET /organisations/new.json
  def new
    @organisation = Organisation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @organisation }
    end
  end

  # GET /organisations/1/edit
  def edit
    @organisation = Organisation.find(params[:id])
  end

  # POST /organisations
  # POST /organisations.json
  def create
    @organisation = Organisation.new(params[:organisation])

    respond_to do |format|
      if @organisation.save
        format.html { redirect_to @organisation, notice: 'Organisation was successfully created.' }
        format.json { render json: @organisation, status: :created, location: @organisation }
       else
        format.html { render action: "new" }
        format.json { render json: @organisation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /organisations/1
  # PUT /organisations/1.json
  def update
    @organisation = Organisation.find(params[:id])

    respond_to do |format|
      if @organisation.update_attributes(params[:organisation])
        format.html { redirect_to @organisation, notice: 'Organisation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @organisation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organisations/1
  # DELETE /organisations/1.json
  def destroy
    @organisation = Organisation.find(params[:id])

    if @auth.is_admin?
      @organisation.destroy
      redirect_to organisations_path
    else
      redirect_to organisations_path
    end

  end

  def add_person
    @organisation = Organisation.find(params[:id])
  end

  def create_person
    @organisation = Organisation.find(params[:id])
    @organisation.people << Person.find(params[:person])
    @organisation.save
    redirect_to @organisation
  end
end

app/views/organisations/_form.html.erb
<%= form_for @organisation do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <br>
  <%= f.label :phone %>
  <%= f.text_field :phone %>
  <br>
  <%= f.label :state %>
  <%= f.text_field :state %>
  <br>
  <%= f.submit %>
<% end %>

app/views/organisations/add_person.html.erb
<%= form_tag [:create_person, @organisation] do %>

	<%= select_tag :person, options_from_collection_for_select(Person.all,:id, :name) %>
	<%= submit_tag 'add' %>
<% end %>

app/views/organisations/create.html.erb
<h1>EventsController#create</h1>
<p>Find me in app/views/events_controller/create.html.erb</p>

app/views/organisations/destroy.html.erb
<h1>EventsController#destroy</h1>
<p>Find me in app/views/events_controller/destroy.html.erb</p>

app/views/organisations/edit.html.erb
<h1>Edit organisation</h1>
<%= render :partial => 'form' %>

app/views/organisations/index.html.erb
<div>
  <h3>Search for Organisation</h3>
    <ul>
      <% @organisations.each do |organisations| %>
      <li><%= link_to(organisations.name, organisations) %></li>
      <% end %>
    </ul>
      <%= form_tag organisations_path, :method => :get do %>
      <%= label_tag :name %>
      <%= text_field_tag :searchname %>

        <br>
      <%= submit_tag 'search' %>
      <% end %>
    </p>
</div>
<!--
<ul>
<% @organisations.each do |organisation| %>
<li><%= link_to(organisation.name, organisation) %></li>
<% end %>
</ul>

<ul>

app/views/organisations/new.html.erb
<h1>New organisation</h1>
<%= render :partial => 'form' %>

app/views/organisations/show.html.erb
<h2><%= @organisation.name %> <%= @organisation.address %> </h2>
<p>Members:

<ul>
      <% @organisation.people.each do |person| %>
      <li><%= person.name %> <%= person.surname %></li>
      <% end %>
    </ul>
  </p>

<button><p><%= link_to 'Add new person to organisation', add_person_organisation_path(@organisation) %></p></button>
</p>
<button><%= link_to 'Edit', edit_organisation_path(@organisation) %></button>
<button><%= link_to 'Delete', @organisation, :method => :delete %></button>
</p>

<div class="container-fluid form_a">
  <div class="row-fluid">
  <div class="span6">
    <h1><%= @organisation.name %></h1>
    <table class="table">
      <tr>
        <td>Name: <%= @organisation.name %></tr>
      <tr>
        <td>Address: <%= @organisation.address %><td><td> State: <%= @organisation.state%></td>
      </tr>
      <tr><td>Phone: <%= @organisation.phone %><td>
      </tr>
      <tr>
      </tr>
    </table>
  </div>
<div class="container-fluid form_b">
  <div class="row-fluid">
    <div class="span6">
      <h1>CALENDAR</h1>
    </div>
  <div class="row-fluid">
    <div class="span6">
      <h1>EVENT NOTES</h1>
      <table class="table">
      <tr><td>sdfasdf<td><td>sdfasdf<td><td>sdfasdf<td></tr>
  </div>
</div>

app/views/organisations/update.html.erb
<h1>EventsController#update</h1>
<p>Find me in app/views/events_controller/update.html.erb</p>