config/routes.rb
Crmpro::Application.routes.draw do
  root :to => 'home#landing'
  get '/home' => 'home#home'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  get '/people' => 'people#index'
  resources :events
  resources :organisations do
  		member do
  			get :add_person
  			post :create_person
  		end
  end

  resources :people do
      member do
        get :add_event
        post :create_event
      end
  end

end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id         :integer          not null, primary key
#  eventtype  :string(255)
#  startdate  :datetime
#  notes      :text
#  person_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  enddate    :datetime
#

class Event < ActiveRecord::Base
  attr_accessible :startdate, :notes, :eventtype, :enddate
  belongs_to	:person
  belongs_to :organisation

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authorize

  def authorize
    if @auth
    else
      redirect_to login_path
    end
  end
  # GET /organisations
  # GET /organisations.json
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end
# GET /people/1
  # GET /people/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /people/new
  # GET /people/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /people/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /people
  # POST /people.json
  def create
    @event = Event.new(params[:event])
    @event.person = @auth

    cal = Google::Calendar.new(:username => 'zoilism@gmail.com',
                           :password => 'Darren12',
                           :app_name => 'zoilism.com-googlecalendar-integration')

event = cal.create_event do |e|
  e.title = params[:event][:eventtype]
  e.start_time = @event.startdate #params[:event][:startdate].to_s
  e.end_time = @event.enddate #params[:event][:startdate].to_s  # seconds * min
end

# puts event

# event = cal.find_or_create_event_by_id(event.id) do |e|
#   e.title = params[:eventtype]
#   e.end_time = params[:startdate] + (60 * 60 * 2) # seconds * min * hours
# end

# puts event

# # All events
# puts cal.events

# # Query events
# puts cal.find_events('my search string')

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /people/1
  # PUT /people/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @event = Event.find(params[:id])

    if @auth.is_admin?
      @event.destroy
      redirect_to events_path
    else
      redirect_to events_path
    end

  end
end

app/views/events/_form.html.erb
<%= form_for @event do |f| %>

  <%= f.label :start_date %>
  <%= f.datetime_select :startdate%>
  <br>
  <%= f.label :end_date %>
  <%= f.datetime_select :enddate%>
  <br>
  <%= f.label :notes %>
  <%= f.text_field :notes %>
  <br>
  <%= f.label :event_type %>
  <%= f.text_field :eventtype %>
  <br>
  <%= f.submit %>
<% end %>

app/views/events/create.html.erb
<h1>EventsController#create</h1>
<p>Find me in app/views/events_controller/create.html.erb</p>

app/views/events/destroy.html.erb
<h1>EventsController#destroy</h1>
<p>Find me in app/views/events_controller/destroy.html.erb</p>

app/views/events/edit.html.erb
<h1>Edit event</h1>
<%= render :partial => 'form' %>

app/views/events/index.html.erb
<ul>
<% @events.each do |event| %>
<li><%= link_to(event.eventtype, event) %></li>

<% end %>
</ul>



GDAY EVENTS
<p>
<%= @events %>	
</p>

app/views/events/new.html.erb
<h1>New event</h1>
<%= render :partial => 'form' %>

app/views/events/show.html.erb
<h2><%= @event.eventtype %> <%= @event.startdate %> </h2>
<p>Notes:<%= @event.notes %></p>
<p>
<button><%= link_to 'Edit', edit_event_path(@event) %></button>
<button><%= link_to 'Delete', @event, :method => :delete %></button>
</p>

app/views/events/update.html.erb
<h1>EventsController#update</h1>
<p>Find me in app/views/events_controller/update.html.erb</p>